apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-application
spec:
  workspaces:
      - name: source
  params:
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: ./
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
  steps:
    - name: deploy-app-to-k8s
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(workspaces.source.path)/$(params.pathToContext)/$(inputs.params.pathToYamlFile)"
