apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-push-angular-project
spec:
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
  pipelineSpec:
    workspaces:
      - name: shared-workspace
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: shared-workspace
        params:
          - name: url
            value: https://github.com/angularexample/angular-8-example-app
          - name: subdirectory
            value: ""
          - name: deleteExisting
            value: "true"
      - name: install-dependencies
        taskRef:
          name: npm-build
        workspaces:
          - name: source
            workspace: shared-workspace
        params:
          - name: PATH_CONTEXT
            value: "."
          - name: ARGS
            value:
              - install
        runAfter:
          - fetch-repository
      - name: build-project
        taskRef:
          name: npm-build
        workspaces:
          - name: source
            workspace: shared-workspace
        params:
          - name: PATH_CONTEXT
            value: "."
          - name: ARGS
            value:
              - run 
              - build
        runAfter:
          - install-dependencies
      - name: list-project
        taskRef:
          name: command
        workspaces:
          - name: source
            workspace: shared-workspace
        runAfter:
          - build-project