apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: command
spec:
  description: Execute a bash command
  workspaces:
    - name: source
  steps:
    - name: show-folder
      image: alpine
      command: ["ls"]
      workingDir: $(workspaces.source.path)
      args:
        - "$(workspaces.source.path)"